stages:
  - deploy

pages:
  stage: deploy
  image: node:22-alpine
  cache:
    key: yarn-$CI_COMMIT_REF_SLUG
    paths:
      - .yarn/cache/
  before_script:
    - corepack enable
  script:
    - yarn install --immutable
    - yarn pull
    - yarn build
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "schedule"